[build]
# Commande de construction qui sera exécutée par Netlify
command = "hugo"
# Le répertoire que Hugo crée et que Netlify doit publier
publish = "public"

[build.environment]
# Ceci indique à Netlify quelle version de Hugo installer
HUGO_VERSION = "0.125.1"